import json

def main():
    # Attempt to load json with common encodings to avoid Windows redirection encoding issues
    data = None
    for encoding in ["utf-8", "utf-8-sig", "utf-16", "utf-16-le", "cp1252"]:
        try:
            with open("temp_seo.json", "r", encoding=encoding) as f:
                data = json.load(f)
                break
        except Exception:
            continue

    if data is None:
        print("Error: Could not decode temp_seo.json using standard encodings.")
        return

    title = data.get("title", "Missing")
    description = data.get("meta_description", "Missing")
    canonical = data.get("canonical", "Missing")
    h1s = data.get("h1", [])
    h2s = data.get("h2", [])
    h3s = data.get("h3", [])
    images = data.get("images", [])
    schemas = data.get("schema", [])
    word_count = data.get("word_count", 0)
    missing_alts = sum(1 for img in images if not img.get("alt"))

    # Format Markdown Report
    report = f"""# StoryGrid Media SEO Audit Report

This audit was generated by executing the `claude-seo` python engine on your live site.

## 📊 Quick Summary

| Metric | Found | Status |
|--------|-------|--------|
| **Title** | "{title}" | {"✅ Valid" if title and len(title) <= 60 else "⚠️ Optimize"} |
| **Meta Description** | "{description}" | {"✅ Valid" if description and len(description) <= 160 else "⚠️ Optimize"} |
| **Canonical URL** | `{canonical}` | ✅ Configured |
| **Word Count** | {word_count} words | ✅ Healthy |
| **Primary H1** | "{h1s[0] if h1s else 'None'}" | {"✅ Unique" if len(h1s) == 1 else "⚠️ Fix"} |
| **Images** | {len(images)} detected | {f"⚠️ {missing_alts} missing alt tags" if missing_alts else "✅ Alt tags present"} |
| **Structured Data** | {len(schemas)} schemas detected | ✅ High-performance JSON-LD |

---

## 🛠️ Action Items & Findings

"""
    issues = []
    if not title or title == "Missing":
        issues.append("- **Critical**: Missing page title.")
    elif len(title) > 60:
        issues.append(f"- **Medium**: Title is a bit long ({len(title)} chars). Keep under 60.")
        
    if not description or description == "Missing":
        issues.append("- **Critical**: Missing meta description.")
    elif len(description) > 160:
        issues.append(f"- **Medium**: Meta description is a bit long ({len(description)} chars). Keep under 160.")

    if len(h1s) == 0:
        issues.append("- **Critical**: Missing H1 tag.")
    elif len(h1s) > 1:
        issues.append(f"- **High**: Multiple H1 tags detected ({len(h1s)} tags). Only use one H1 per page.")

    if missing_alts > 0:
        issues.append(f"- **High**: {missing_alts} out of {len(images)} images are missing `alt` attributes.")

    if issues:
        report += "\n".join(issues) + "\n"
    else:
        report += "✅ No critical SEO issues found on the analyzed page!\n"

    report += f"""
---

## 🏷️ Schema Markup Detected ({len(schemas)})

We successfully detected the JSON-LD Service schema we injected:
"""
    for i, schema in enumerate(schemas):
        schema_type = schema.get("@type", "Unknown")
        name = schema.get("serviceType", schema.get("name", "Unnamed"))
        report += f"- **Schema #{i+1}**: `{schema_type}` ({name})\n"

    report += """
---
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Built by agricidaniel — Join the AI Marketing Hub community
🆓 Free  → https://www.skool.com/ai-marketing-hub
⚡ Pro   → https://www.skool.com/ai-marketing-hub-pro
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

    with open("AUDIT-REPORT.md", "w", encoding="utf-8") as f:
        f.write(report)

    print("Success: Generated AUDIT-REPORT.md")

if __name__ == "__main__":
    main()
